version: 2
updates:
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: '/apps/api'
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: '/app/web'
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: '/misc/docker'
  schedule:
    interval: daily
