name: scheduler

services:
  db:
    container_name: db
    image: akorn/postgres:18-scratch
    restart: always
    read_only: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    #command: postgres -c 'log_statement=all'
    ports:
      - 127.0.0.1:5432:5432
    tmpfs:
      - /run/postgresql:rw,noexec,nosuid,size=5m
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db

  api:
    container_name: api
    depends_on:
      - db
    image: akorn/scheduler
    restart: always
    read_only: true
    stop_signal: SIGINT
    environment:
      - DSN=postgres://postgres:@db:5432/postgres?sslmode=disable
    ports:
      - 8080:8080
    networks:
      - api
      - db

volumes:
  db:

networks:
  db:
  api:
